language: python
python:
  - "3.5"
  - "3.6"

sudo: false

env:
  - TOXENV=py27-django18
  - TOXENV=py27-django19
  - TOXENV=py27-django110
  - TOXENV=py27-djangomaster
  - TOXENV=py34-django18
  - TOXENV=py34-django19
  - TOXENV=py34-django110
  - TOXENV=py34-djangomaster
  - TOXENV=py35-django18
  - TOXENV=py35-django19
  - TOXENV=py35-django110
  - TOXENV=py35-djangomaster
  - TOXENV=py36-djangomaster
  - TOXENV=docs

matrix:
  fast_finish: true

install:
  - pip install tox "virtualenv<14"
  - pip install coveralls

script:
  - tox

after_script:
  - coveralls
