# https://travis-ci.org/jazzband/django-oauth-toolkit
dist: bionic

language: python

cache:
  directories:
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/.tox

# Make sure to coordinate changes to envlist in tox.ini.
matrix:
  allow_failures:
    - env: TOXENV=py36-djangomaster
    - env: TOXENV=py37-djangomaster      
    - env: TOXENV=py38-djangomaster
    - env: TOXENV=py39-djangomaster

  include:
    - python: 3.7
      env: TOXENV=py37-flake8
    - python: 3.7
      env: TOXENV=py37-docs

    - python: 3.9
      env: TOXENV=py39-djangomaster
    - python: 3.9
      env: TOXENV=py39-django30
    - python: 3.9
      env: TOXENV=py39-django22

    - python: 3.8
      env: TOXENV=py38-django30
    - python: 3.8
      env: TOXENV=py38-django22
    - python: 3.8
      env: TOXENV=py38-django21
    - python: 3.8
      env: TOXENV=py38-djangomaster

    - python: 3.7
      env: TOXENV=py37-django30
    - python: 3.7
      env: TOXENV=py37-django22
    - python: 3.7
      env: TOXENV=py37-django21
    - python: 3.7
      env: TOXENV=py37-djangomaster

    - python: 3.6
      env: TOXENV=py36-django22
    - python: 3.6
      env: TOXENV=py36-django21

    - python: 3.5
      env: TOXENV=py35-django22
    - python: 3.5
      env: TOXENV=py35-django21

install:
  - pip install coveralls tox tox-travis

script:
  - tox

after_script:
  - coveralls
