language: python
python: "2.7"
sudo: false

env:
  - TOX_ENV=py27-django17
  - TOX_ENV=py27-django18
  - TOX_ENV=py27-django19
  - TOX_ENV=py32-django17
  - TOX_ENV=py32-django18
  - TOX_ENV=py33-django17
  - TOX_ENV=py33-django18
  - TOX_ENV=py34-django17
  - TOX_ENV=py34-django18
  - TOX_ENV=py34-django19
  - TOX_ENV=py35-django18
  - TOX_ENV=py35-django19
  - TOX_ENV=docs

matrix:
  include:
    - python: 3.5
      env:
        - TOX_ENV=py35-django18
        - TOX_ENV=py35-django19

install:
  - pip install tox
  - pip install coveralls

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls
