language: python
python:
  - "3.5"

sudo: false

env:
  - TOX_ENV=py27-django18
  - TOX_ENV=py27-django19
  - TOX_ENV=py32-django18
  - TOX_ENV=py33-django18
  - TOX_ENV=py34-django18
  - TOX_ENV=py34-django19
  - TOX_ENV=py35-django18
  - TOX_ENV=py35-django19
  - TOX_ENV=docs

matrix:
  fast_finish: true

install:
  - pip install tox "virtualenv<14"
  - pip install coveralls

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls
