language: python
python:
  - "3.6"

sudo: false

env:
  - TOXENV=py27-django18
  - TOXENV=py27-django19
  - TOXENV=py27-django110
  - TOXENV=py27-django111
  - TOXENV=py34-django18
  - TOXENV=py34-django19
  - TOXENV=py34-django110
  - TOXENV=py34-django111
  - TOXENV=py35-django18
  - TOXENV=py35-django19
  - TOXENV=py35-django110
  - TOXENV=py35-django111
  - TOXENV=py35-djangomaster
  - TOXENV=py36-django111
  - TOXENV=py36-djangomaster
  - TOXENV=docs

matrix:
  fast_finish: true
  allow_failures:
    - env: TOXENV=py35-djangomaster
    - env: TOXENV=py36-djangomaster

install:
  - pip install coveralls tox "virtualenv<14"

script:
  - tox

after_script:
  - coveralls
